---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: my-vm
spec:
  forProvider:
    ami: ami-0d3a2960fcac852bc
    region: eu-north-1
    instanceType: t3.nano
    subnetIdRef:
      name: my-vm
    tags:
      Name: my-vm
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InstanceState
metadata:
  name: my-vm
spec:
  forProvider:
    region: eu-north-1
    instanceIdRef:
      name: my-vm
    state: running
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: my-vm
spec:
  forProvider:
    region: eu-north-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: my-vm
spec:
  forProvider:
    region: eu-north-1
    availabilityZone: eu-north-1a
    cidrBlock: 10.0.0.0/24
    vpcIdRef:
      name: my-vm
    mapPublicIpOnLaunch: true
